### ISSUE TITLE
TypeError: unsupported operand type(s)

### ISSUE THREAD

**Issue by rchastain** [intothevoid/knightfight#6]
Hello!
The project looks very cool.
I get this error when I try to run it.

```
[roland@localhost knightfight (main)]$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: chess==1.9.4 in /home/roland/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (1.9.4)
Collecting click==8.1.3
  Downloading click-8.1.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 992.0 kB/s eta 0:00:00
Collecting mypy-extensions==0.4.3
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Collecting packaging==23.0
  Downloading packaging-23.0-py3-none-any.whl (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.7/42.7 KB 651.5 kB/s eta 0:00:00
Collecting pathspec==0.11.0
  Downloading pathspec-0.11.0-py3-none-any.whl (29 kB)
Collecting platformdirs==2.6.2
  Downloading platformdirs-2.6.2-py3-none-any.whl (14 kB)
Collecting pygame==2.1.2
  Downloading pygame-2.1.2-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (21.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.8/21.8 MB 2.9 MB/s eta 0:00:00
Collecting pytoolconfig==1.2.5
  Downloading pytoolconfig-1.2.5-py3-none-any.whl (16 kB)
Requirement already satisfied: PyYAML==6.0 in /home/roland/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (6.0)
Collecting tomli==2.0.1
  Downloading tomli-2.0.1-py3-none-any.whl (12 kB)
Installing collected packages: mypy-extensions, tomli, pygame, platformdirs, pathspec, packaging, click, pytoolconfig
Successfully installed click-8.1.3 mypy-extensions-0.4.3 packaging-23.0 pathspec-0.11.0 platformdirs-2.6.2 pygame-2.1.2 pytoolconfig-1.2.5 tomli-2.0.1
[roland@localhost knightfight (main)]$ python main.py
pygame 2.1.2 (SDL 2.0.16, Python 3.8.14)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from knightfight.board import Board
  File "/home/roland/Documents/echecs/sources/python/knightfight/knightfight/board.py", line 9, in <module>
    from helpers.pychess import add_move_to_engine_state
  File "/home/roland/Documents/echecs/sources/python/knightfight/helpers/pychess.py", line 10, in <module>
    start: Optional[GridPosition | None],
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

**Comment by intothevoid** [comment]
Hi Roland,

Thank you! I've pushed a fix to the main branch which should fix your error. Could you please try again and let me know how you go?

Cheers.

**Comment by rchastain** [comment]
Yes, it works now. And honestly it's a very beautiful game!

The window is a little too large for my screen. Is it possible to change the size in source code?

Is it possible to use any UCI engine, or is the GUI designed specifically for Stockfish?

I like very much the idea of the two very simple Python scripts as opponents.

**Comment by intothevoid** [comment]
Thank you Roland! Appreciate the feedback. You should be able to adjust sizes by editing the config.yml although I have not tested this out. The game supports any UCI engine supported by pychess. See https://python-chess.readthedocs.io/en/latest/engine.html to understand how the UCI engine is loaded. You should be able to modify the code quite easily to support other engines.
